spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///slsaledb?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT8
    serialization:
      write-dates-as-timestamps: false

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
